version: '2'
services:
    termpaper-app:
        image: termpaper
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/termpaperlocal?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://termpaper-elasticsearch:9200
        ports:
            - 8080:8080
    termpaper-mysql:
        extends:
            file: mysql.yml
            service: termpaper-mysql
    termpaper-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: termpaper-elasticsearch
